### ISSUE TITLE
Minecraft Forge 1.15.2 won't launch with latest version of RFTools Base, etc.  

### ISSUE THREAD

**Issue by MattRidge** [McJtyMods/RFToolsBase#9] opened 2020-03-24 20:42 UTC
Sorry, my son was playing around the computer before I could respond.  Minecraft Forge is outright crashing when I try to run the base.  I'll attach the crash files in a minute.

**Comment by MattRidge** [comment] 2020-03-24 20:47
[logs.zip](https://github.com/McJtyMods/RFToolsBase/files/4377598/logs.zip)
Here are the logs

**Comment by LoganDark** [comment] 2020-04-21 04:27
[crash-2020-04-20_21.17.14-client.txt](https://github.com/McJtyMods/RFToolsBase/files/4507614/crash-2020-04-20_21.17.14-client.txt)

<details><summary>Exception</summary><pre>java.lang.RuntimeException: java.lang.reflect.InvocationTargetException<br>	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78) ~[?:31.1] {re:classloading}<br>	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:234) ~[?:?] {re:classloading}<br>	at net.minecraftforge.fml.ModLoader.lambda$buildMods$26(ModLoader.java:214) ~[?:?] {re:classloading}<br>	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212] {}<br>	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212] {}<br>	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212] {}<br>	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:216) ~[?:?] {re:classloading}<br>	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$18(ModLoader.java:173) ~[?:?] {re:classloading}<br>	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212] {}<br>	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212] {}<br>	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212] {}<br>	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212] {}<br>	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212] {}<br>	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) ~[?:?] {re:classloading}<br>	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}<br>	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}<br>	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}<br>	at net.minecraft.client.Minecraft.&lt;init&gt;(Minecraft.java:393) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation/MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}<br>	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.1.46.jar:?] {re:classloading}<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212] {}<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212] {}<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212] {}<br>	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.46.jar:31.1] {}<br>	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}<br>	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}<br>	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}<br>	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>Caused by: java.lang.reflect.InvocationTargetException<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212] {}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212] {}<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212] {}<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.1] {re:classloading}<br>	... 35 more<br>Caused by: net.minecraftforge.fml.ModLoadingException: RFToolsBase has class loading errors<br>§7mcjty/lib/base/ModBase<br>	at net.minecraftforge.fml.javafmlmod.FMLModContainer.&lt;init&gt;(FMLModContainer.java:77) ~[?:31.1] {re:classloading}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212] {}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212] {}<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212] {}<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.1] {re:classloading}<br>	... 35 more<br>Caused by: java.lang.NoClassDefFoundError: mcjty/lib/base/ModBase<br>	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_212] {}<br>	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}<br>	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212] {}<br>	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLModContainer.&lt;init&gt;(FMLModContainer.java:71) ~[?:31.1] {re:classloading}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212] {}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212] {}<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212] {}<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.1] {re:classloading}<br>	... 35 more<br>Caused by: java.lang.ClassNotFoundException: mcjty.lib.base.ModBase<br>	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212] {}<br>	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212] {}<br>	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_212] {}<br>	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}<br>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}<br>	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212] {}<br>	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLModContainer.&lt;init&gt;(FMLModContainer.java:71) ~[?:31.1] {re:classloading}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212] {}<br>	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212] {}<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212] {}<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212] {}<br>	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.1] {re:classloading}<br>	... 35 more</pre></details>

Here's the error itself. I hate having to unzip log files and then open them in a text editor to see what the error is.

Highlights:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: net.minecraftforge.fml.ModLoadingException: RFToolsBase has class loading errors
Caused by: java.lang.NoClassDefFoundError: mcjty/lib/base/ModBase
Caused by: java.lang.ClassNotFoundException: mcjty.lib.base.ModBase
```

This crash report is my own by the way. I also have this issue.

**Comment by McJty** [comment] 2020-04-21 05:02
Do you have McJtyLib?

**Comment by LoganDark** [comment] 2020-04-21 05:06
Can you please use Curse's dependency system so that installing mods through Twitch automatically installs the dependencies?

No, I didn't. I think that was the problem. thanks.

**Comment by McJty** [comment] 2020-04-21 05:12
I do use the Curse dependency system. McJtyLib is properly marked as a required dependency for all my mods. Not sure why it wasn't working for you

**Comment by McJty** [comment] 2020-04-21 05:12
![image](https://user-images.githubusercontent.com/8188472/79827768-7db0d100-839f-11ea-8733-ae001a3c800d.png)

**Comment by LoganDark** [comment] 2020-04-21 05:13
Huh. I downloaded from Curse directly but I swear I looked for dependencies on the page. Maybe that is a Curse UI issue.

**Comment by MokahTGS** [comment] 2020-09-03 22:06
We are seeing this issue as well.  Trying to load we get a CTD.

Crash Log: https://pastebin.com/WJixFsQb

Full mod list: https://pastebin.com/zpQyK2k6

MC 1.15.2
Forge 31.2.33
mcjtylib-1.15-4.1.7.jar
theoneprobe-1.15-2.0.7.jar
rftoolsbase-1.15-1.1.6.jar
rftoolsbuilder-1.15-2.1.8.jar
rftoolscontrol-1.15-3.0.7.jar
rftoolspower-1.15-2.2.4.jar
rftoolsstorage-1.15-1.1.9.jar
rftoolsutility-1.15-2.1.5-beta.jar

**Comment by McJty** [comment] 2020-09-04 03:08
Update to latest RFTools Utility. 2.1.5-beta is not the latest

**Closed as completed by McJty** 2020-09-04 03:08 UTC
